/*
The MIT License (MIT)

Copyright (c) 2016 Roman Alarcon

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "SMCppSkeletons.h"
#include <string>

/**
 *
 */
std::string SMCppSkeletons::makeFileHeadingComment(const std::string& filename)
{
    return 
        "//\n"
        "// " + filename + "\n"
        "// File generated by smmake v0.1. Do not edit!\n"
        "//\n";
}

std::string SMCppSkeletons::makeIfDefHeading(const std::string& filename)
{
    std::string identifier = "__";
    
    for(std::string::const_iterator it = filename.begin(); it != filename.end(); ++it)
    {
        if(*it != ' ')
        {
            identifier += (*it == '.') ? '_' : ::toupper(*it);
        } 
    }
    
    return "#ifndef " + identifier + "\n#define " + identifier;
}

std::string SMCppSkeletons::stateHeaderSkeleton(const std::string& prefixAndName)
{
    return
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "[STATE_NAME].h") +
        SMCppSkeletons::makeIfDefHeading(prefixAndName + "[STATE_NAME]_H") + 
        "\n\n"
        "#include \"" + prefixAndName + "BaseState.h\"\n\n"
        "namespace [NAMESPACE]\n{\n\n"
        "class " + prefixAndName + "[STATE_NAME] : public " + prefixAndName + "BaseState\n"
        "{\n"
        "private:\n"
        "    static " + prefixAndName + "[STATE_NAME] * _sharedInstance;\n" 
        "\n"
        "public:\n"
        "    static " + prefixAndName + "[STATE_NAME] * sharedInstance();\n"
        "    virtual std::string getStateName() const;\n"
        "\n"
        "private:\n"
        "[EVENTS]\n"
        "};\n\n"
        "}\n\n"
        "#endif\n";
}

std::string SMCppSkeletons::stateImplementationSkeleton(const std::string& prefixAndName)
{
    return 
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "[STATE_NAME].cpp") +
        "\n"
        "[INCLUDES]\n"
        "namespace [NAMESPACE]\n{\n\n"
        "\n"
        "" + prefixAndName + "[STATE_NAME] * " + prefixAndName + "[STATE_NAME]::_sharedInstance = NULL;\n"
        "\n"
        "" + prefixAndName + "[STATE_NAME] * " + prefixAndName + "[STATE_NAME]::sharedInstance()\n"
        "{\n"
        "    if(_sharedInstance == NULL)\n"
        "    {\n"
        "        _sharedInstance = new " + prefixAndName + "[STATE_NAME];\n"
        "    }\n"
        "\n"
        "    return _sharedInstance;\n"
        "}\n\n"
        "std::string " + prefixAndName + "[STATE_NAME]::getStateName() const\n"
        "{\n"
        "    return \"" + prefixAndName + "[STATE_NAME]\";\n"
        "}\n\n"
        "[EVENTS]\n"
        "}\n";
}


std::string SMCppSkeletons::baseStateDeclarationSkeleton(const std::string& prefixAndName)
{
    return
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "BaseState.h") +
        SMCppSkeletons::makeIfDefHeading(prefixAndName + "BaseState_H") + 
        "\n\n"
        "#include \"" + prefixAndName + "StateDelegate.h\"\n"
        "namespace [NAMESPACE]\n{\n\n"
        "\n"
        "class " + prefixAndName + "BaseState\n"
        "{\n"
        "protected:\n"
        "    " + prefixAndName + "StateDelegate * _delegate;\n"
        "\n"
        "protected:\n"
        "    void changeState(" + prefixAndName + "BaseState * newState);\n"
        "\n"
        "public:\n"
        "[EVENTS]\n"
        "\n"
        "    void setDelegate(" + prefixAndName + "StateDelegate * delegate);\n"
        "    virtual std::string getStateName() const;\n"
        "};\n\n"
        "}\n\n"
        "#endif\n";   
}

std::string SMCppSkeletons::baseStateImplementationSkeleton(const std::string& prefixAndName)
{
    return 
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "BaseState.m") +
        "\n"
        "#include \"" + prefixAndName + "BaseState.h\"\n"
        "#include <iostream>\n\n"
        "namespace [NAMESPACE]\n{\n\n"
        "\n"
        "[EVENTS]\n"
        "void " + prefixAndName + "BaseState::setDelegate(" + prefixAndName + "StateDelegate * delegate)\n"
        "{\n"
        "    _delegate = delegate;\n"
        "}\n\n"
        "void " + prefixAndName + "BaseState::changeState(" + prefixAndName + "BaseState * newState)\n"
        "{\n"
        "    if(newState == NULL)\n"
        "    {\n"
        "        std::cerr << \"**** ERROR **** Target state is null\" << std::endl;\n"
        "    }\n"
        "\n"
        "    _delegate->" + prefixAndName + "ChangeState(newState);\n"
        "}\n\n"
        "std::string " + prefixAndName + "BaseState::getStateName() const\n"
        "{\n"
        "    return  \"" + prefixAndName + "BaseState\";"
        "}\n\n"
        "}\n";
}

/**
 *
 */
std::string SMCppSkeletons::generateDelegateSkeleton(const std::string& prefixAndName)
{
    return 
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "StateDelegate.h") +
        SMCppSkeletons::makeIfDefHeading(prefixAndName + "StateDelegate_H") + 
        "\n\n"
        "#include <map>\n"
        "#include <string>\n\n"
        "namespace [NAMESPACE]\n{\n\n"
        "typedef std::map<std::string, std::string> Parameters;\n" 
        "\n"
        "class " + prefixAndName + "BaseState;\n" +
        "\n" +
        "class " + prefixAndName + "StateDelegate\n" +
        "{\n" +
        "public:\n" +
        "[ACTIONS]\n\n" +
        "    virtual void " + prefixAndName + "ChangeState(" + prefixAndName + "BaseState * newState) { /* Hook */ };\n" +
        "};" + 
        "\n\n" +
        "}\n\n"
        "#endif\n";
}

std::string SMCppSkeletons::generateConfiguratorHeaderSkeleton(const std::string& prefixAndName)
{
    return
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "Configurator.h") +
        SMCppSkeletons::makeIfDefHeading(prefixAndName + "Configurator_H") + 
        "\n\n"
        "#include \"" + prefixAndName + "StateDelegate.h\"\n\n" +
        "namespace [NAMESPACE]\n{\n\n"
        "\n" +
        "class " + prefixAndName + "Configurator\n" +
        "{\n" +
        "private:\n"
        "    static " + prefixAndName + "Configurator * _sharedInstance;\n" 
        "\n" +
        "public:\n"
        "    static " + prefixAndName + "Configurator * sharedInstance();\n" +
        "\n" +
        "    virtual void setAllStatesDelegate(" + prefixAndName + "StateDelegate * delegate);\n" +
        "\n" +
        "};\n\n" +
        "}\n\n"
        "#endif\n";
} 

std::string SMCppSkeletons::generateConfiguratorImplementationSkeleton(const std::string& prefixAndName)
{
    return 
        SMCppSkeletons::makeFileHeadingComment(prefixAndName + "Configurator.cpp") +
        "\n"
        "#include \"" + prefixAndName + "Configurator.h\"\n" +
        "[INCLUDES]\n" +
        "namespace [NAMESPACE]\n{\n\n"
        "\n" +
         "\n" +
         "" + prefixAndName + "Configurator * " + prefixAndName + "Configurator::_sharedInstance = NULL;\n" +
         "\n" +
         "" + prefixAndName + "Configurator * " + prefixAndName + "Configurator::sharedInstance()\n" +
         "{\n"
         "    if(_sharedInstance == NULL)\n"
         "    {\n"
         "        _sharedInstance = new " + prefixAndName + "Configurator;\n"
         "    }\n"
         "\n"
         "    return _sharedInstance;\n"
         "}\n"
         "\n" +
         "void " + prefixAndName + "Configurator::setAllStatesDelegate(" + prefixAndName + "StateDelegate * delegate)\n" +
         "{\n" +
         "[ASSOCIATIONS]\n" +
         "}\n" +
         "\n" +
         "}\n";
} 


