/*
The MIT License (MIT)

Copyright (c) 2016 Roman Alarcon

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "SMObjectiveCSkeletons.h"

#include <iostream>
#include <string>

/**
 *
 */
std::string SMObjectiveCSkeletons::makeFileHeadingComment(const std::string& filename)
{
    return 
        "//\n"
        "// " + filename + "\n"
        "// File generated by smmake v0.1. Do not edit!\n"
        "//\n";
}

std::string SMObjectiveCSkeletons::stateHeaderSkeleton(const std::string& prefixAndName)
{
    return 
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "[STATE_NAME].h") +
        "\n"
        "#import \"" + prefixAndName + "BaseState.h\"\n"
        "\n"
        "@interface " + prefixAndName + "[STATE_NAME] : " + prefixAndName + "BaseState\n"
        "\n"
        "+(" + prefixAndName + "[STATE_NAME] *) sharedInstance;\n"
        "\n"
        "@end";
}

std::string SMObjectiveCSkeletons::stateImplementationSkeleton(const std::string& prefixAndName)
{
    return 
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "[STATE_NAME].m") +
        "\n"
        "[IMPORTS]\n"
        "\n"
        "@implementation " + prefixAndName + "[STATE_NAME]\n"
        "\n"
        "static " + prefixAndName + "[STATE_NAME] *sharedInstance = nil;\n"
        "\n"
        "+ (" + prefixAndName + "[STATE_NAME] *) sharedInstance\n"
        "{\n"
        "    static dispatch_once_t onceToken;\n"
        "\n"
        "    dispatch_once(&onceToken, ^{\n"
        "        sharedInstance = [[self alloc] init];\n"
        "    });\n"
        "\n"
        "    return sharedInstance;\n"
        "}\n"
        "\n"
        "[EVENTS]\n"
        "@end";
}


std::string SMObjectiveCSkeletons::baseStateDeclarationSkeleton(const std::string& prefixAndName)
{
    return 
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "BaseState.h") +
        "#import <Foundation/Foundation.h>\n"
        "#import \"" + prefixAndName + "StateDelegate.h\"\n"
        "\n"
        "@interface " + prefixAndName + "BaseState : NSObject\n"
        "\n"
        "@property (nonatomic, assign) id<" + prefixAndName + "StateDelegate> delegate;\n"
        "\n"
        "/**\n"
        " * State machine events\n"
        " */\n"
        "\n"
        "[EVENTS]\n"
        "\n"
        "-(void) changeState:(" + prefixAndName + "BaseState *) newState;\n"
        "\n"
        "@end\n";
}

std::string SMObjectiveCSkeletons::baseStateImplementationSkeleton(const std::string& prefixAndName)
{
    return 
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "BaseState.m") +
        "#import \"" + prefixAndName + "BaseState.h\"\n"
        "\n"
        "@implementation " + prefixAndName + "BaseState\n"
        "\n"
        "[EVENTS]\n"
        "-(void) changeState:(" + prefixAndName + "BaseState *) newState\n"
        "{\n"
        "    if(newState == nil)\n"
        "    {\n"
        "        NSLog(@\"**** ERROR **** (%@ --> ERROR)\", [self class]);\n"
        "    }\n"
        "\n"
        "    [self.delegate " + prefixAndName + "ChangeState:newState];\n"
        "}\n\n"
        "@end\n";
}

/**
 *
 */
std::string SMObjectiveCSkeletons::generateDelegateSkeleton(const std::string& prefixAndName)
{
    return
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "StateDelegate.h") +
        "#import <Foundation/Foundation.h>\n\n" +
        "@class " + prefixAndName + "BaseState;\n" +
        "\n" +
        "@protocol " + prefixAndName + "StateDelegate <NSObject>\n" +
        "@optional\n" +
        "\n\n" +
        "[ACTIONS]\n\n" +
        "-(void) " + prefixAndName + "ChangeState:(" + prefixAndName + "BaseState *) newState;\n" +
        "\n" + 
        "@end\n";
}

/**
 *
 */
std::string SMObjectiveCSkeletons::generateConfiguratorImplementationSkeleton(const std::string& prefixAndName)
{
    return
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "Configurator.m") +
        "#import \"" + prefixAndName + "Configurator.h\"\n" +
        "[IMPORTS]\n" +
        "\n" +
        "@implementation " + prefixAndName + "Configurator\n" +
         "\n" +
         "static " + prefixAndName + "Configurator *sharedInstance = nil;\n" +
         "\n" +
         "+(" + prefixAndName + "Configurator *) sharedInstance\n" +
         "{\n" +
         "    static dispatch_once_t onceToken;\n" +
         "\n" +
         "    dispatch_once(&onceToken, ^{\n" +
         "        sharedInstance = [[self alloc] init];\n" +
         "    });\n" +
         "\n" +
         "    return sharedInstance;\n" +
         "}\n" +
         "\n" +
         "-(void) setAllStatesDelegate:(id<" + prefixAndName + "StateDelegate>) delegate\n" +
         "{\n" +
         "[ASSOCIATIONS]\n" +
         "}\n" +
         "\n" +
        "@end\n";
} 

std::string SMObjectiveCSkeletons::generateConfiguratorHeaderSkeleton(const std::string& prefixAndName)
{
    return
        SMObjectiveCSkeletons::makeFileHeadingComment(prefixAndName + "Configurator.h") +
        "#import <Foundation/Foundation.h>\n" +
        "#import \"" + prefixAndName + "StateDelegate.h\"\n" +
        "\n" +
        "@interface " + prefixAndName + "Configurator : NSObject\n" +
        "\n" +
        "+(" + prefixAndName + "Configurator *) sharedInstance;\n" +
        "\n" +
        "-(void) setAllStatesDelegate:(id<" + prefixAndName + "StateDelegate>) delegate;\n" +
        "\n" +
        "@end\n" +
        "\n";
} 

